name: David Cruwys
favicon: null
layout_spectrum: 0.75271
typography_spectrum: 0.49398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000800'
    - '#106b9a'
    - '#8b9b91'
    - '#a9c7c7'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
